# Generated by Django 2.2.1 on 2019-08-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=12)),
                ('contact', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=12)),
            ],
        ),
    ]
