# Generated by Django 3.0.2 on 2020-01-16 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0004_auto_20200115_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='media/shop/images'),
        ),
    ]
